const defaultSettings = {
  "theme": "dark",
  "fontFamily": "Fira Code, Menlo, Consolas, monospace",
  "editorFontSize": 15,
  "editorTabSize": 2,
  "editorInsertSpaces": true,
  "editorLineNumbers": "on",
  "autoSave": "onFocusChange",
  "autoSaveDelay": 1000,
  "files.exclude": [
    "build/",
    "node_modules/",
    ".dart_tool/",
    ".git/",
    ".idea/",
    ".vscode/",
    ".codelab_ide/",
  ],
  "explorer.openEditors.visible": 10,
  "window.zoomLevel": 0,
  "terminal.integrated.fontSize": 14,
  "terminal.integrated.cursorBlinking": true,
  "terminal.integrated.fontFamily": "Fira Mono, monospace",
  "keybindings": {
    "save": "Ctrl+S",
    "run": "F5",
    "find": "Ctrl+F",
    "replace": "Ctrl+H",
    "commandPalette": "Ctrl+Shift+P",
    "openFile": "Ctrl+P",
  },
  "snippets.enabled": true,
  "recentProjects": [],
  "linting.enabled": true,
  "linting.autoFixOnSave": false,
  "extensions.recommendations": [],
  "aiAgent": {
    "enabled": true,
    "provider": "openai",
    "model": "gpt-4",
    "maxTokens": 1024,
    "temperature": 0.15,
    "history": true,
    "role": "assistant",
    "personality": "friendly",
    "defaultPrompt": "Помогай писать чистый и понятный код.",
    "apiKey": "",
    "showSuggestionsOnStartup": true,
    "enableInlineCompletion": true,
    "contextWindowLines": 16,
  },
};
