# This file configures the static analysis results for your project (errors,
# warnings, and lints).
#
# This enables the 'recommended' set of lints from `package:lints`.
# This set helps identify many issues that may lead to problems when running
# or consuming Dart code, and enforces writing Dart using a single, idiomatic
# style and format.
#
# If you want a smaller set of lints you can change this to specify
# 'package:lints/core.yaml'. These are just the most critical lints
# (the recommended set includes the core lints).
# The core lints are also what is used by pub.dev for scoring packages.

include: package:lints/recommended.yaml

# Exclude generated files from analysis
analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/*.gr.dart'
  errors:
    # Ignore freezed/json_serializable warnings
    invalid_annotation_target: ignore
    # Ignore deprecated API warnings (will be updated later)
    deprecated_member_use: ignore
    # Ignore dead code in widgets (false positives)
    dead_code: ignore
    dead_null_aware_expression: ignore
    # Ignore unused elements (some are for future use)
    unused_element: ignore
    unused_field: ignore

# Disable specific lints
linter:
  rules:
    # Freezed generates code with multiple underscores
    unnecessary_underscores: false
    # Allow HTML in doc comments for generic types
    unintended_html_in_doc_comment: false
    # Allow Type as parameter name in generic use cases
    avoid_types_as_parameter_names: false

# For more information about the core and recommended set of lints, see
# https://dart.dev/go/core-lints

# For additional information about configuring this file, see
# https://dart.dev/guides/language/analysis-options
